################################################################################
# \file bsp.mk
#
# \brief
# Define the CY8CPROTO-041TP target.
#
################################################################################
# \copyright
# Copyright (c) 2019-2026 Infineon Technologies AG
# an affiliate of Infineon Technologies AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CY8C4147AZQ-T495
DEVICE:=CY8C4147AZQ-T495
DEVICE_COMPONENTS:=CAT2 PSOC4100TP
DEVICE_CY8C4147AZQ-T495_CORES:=CORE_NAME_CM0P_0
DEVICE_CY8C4147AZQ-T495_DIE:=PSOC4NEXT
DEVICE_CY8C4147AZQ-T495_FLASH_KB:=128
DEVICE_CY8C4147AZQ-T495_IPBLOCKS:=M0S8CPUSSV3_S8 M0S8CPUSSV3_S8_V3 M0S8IOSS M0S8IOSS_V1 M0S8MSCV3LP M0S8MSCV3LP_V1 M0S8PASS4A_VER3 M0S8PASS4A_VER3_V3 M0S8PERI M0S8PERI_V1 M0S8TCPWM_VER2 M0S8TCPWM_VER2_V2 M0S8WCO M0S8WCO_V1 MXSCB MXSCB_V3 S8SRSSLT S8SRSSLT_V1
DEVICE_CY8C4147AZQ-T495_SRAM_KB:=32
DEVICE_LIST:=CY8C4147AZQ-T495
DEVICE_TOOL_IDS:=bsp-assistant capsense-configurator capsense-tuner device-configurator dfuh-tool library-manager lin-configurator project-creator sensor-designer-tool smartio-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat2)
